### ISSUE TITLE
Issue reading in LAS 1.4 prf 6 file

### ISSUE THREAD

**Issue by AronBoettcher** [Jean-Romain/rlas#15]
Trying to read in a LAS 1.4 prf 6 and I'm getting an error: 'LAS format not yet supported'
This seems like expected behavior, but.. I really want to read this file.
Is this expected behavior?

**Comment by Jean-Romain** [comment]
Hi, this is an expected behavior because I've never encountered such file type. So, I was not able debug the code and I disabled the support waiting for somebody complaining :smile:. You are the one. Send me a piece of file and I will enable the support of such format.

**Comment by Jean-Romain** [comment]
Hi, do you still need to read LAS1.4 prf 6 file?

**Comment by AronBoettcher** [comment]
Hello, I had to make sure I had permission to share these data. The attached is a LAS1.4 prf 6 file.
[las14_pdrf6_sample.zip](https://github.com/Jean-Romain/rlas/files/1798867/las14_pdrf6_sample.zip)

**Comment by Jean-Romain** [comment]
Thank, I will try to enable the feature tomorrow.

**Comment by Jean-Romain** [comment]
Done in read more. write more is more work. Update your `rlas` version from github

**Comment by AronBoettcher** [comment]
Great, I'll give it a run. Thanks!
