### ISSUE TITLE
CRAN compilation failed on Windows i386

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/rlas#17]
@floriandeboissieu: The windows builder gives an error for rlas 1.2.0 on Windows for 32 bits architecture. https://win-builder.r-project.org/mQ1z5qA5JIY5/. This error is likely in testthat. I can't figure out what is the error. Do you have any idea? A way to reproduce?

**Comment by floriandeboissieu** [comment]
With so little clue in the log... I'll check tomorrow if I can find 
something

Cheers

**Comment by floriandeboissieu** [comment]
Anything with rhub check?

**Comment by Jean-Romain** [comment]
Yep an rhub does not provide more informations. It failed after 1h30.

**Comment by Jean-Romain** [comment]
https://builder.r-hub.io/status/rlas_1.2.0.tar.gz-42dbc6ac7089497d901ef8aa630423c4

**Comment by Jean-Romain** [comment]
I sequentially uploaded 3 versions

1. All the code in `testthat` was commented: :heavy_check_mark: 
2. All the code in `testthat` was commented but `test-head_tools.R` : :x: 
3. All the code in `testthat` was commented but `test-readlas.R` : :heavy_check_mark: 

So the problem seems to come from `test-head_tools.R`. I slowily investigate. One clue each time the CRAN compile the package i.e. once each 15 minutes :smile: 

The big deal is that is that `header_tools` is pure R stuff...

**Comment by Jean-Romain** [comment]
The issue occurs at several place but one of them is ligne 18 of `test_header_tools.R`

```r
wheader = read.lasheader(write_path)
```

However line 5 of the same file this one works

```r
header = read.lasheader(lazfile)
```

**Comment by floriandeboissieu** [comment]
I started the same yesterday, commenting all but:

     - readlas tests -> works

     - writelas tests -> doesn't work

I commented all writelas including back progressively the tests.

**Comment by floriandeboissieu** [comment]
I narrowed to line 43 of test-writelas:

header = read.lasheader(lazfile)

I believe it has something to do with vlrsreader function.

Maybe, it could has something to do with I64 type definition, in 
inst/include/mydefs.hpp (line 61-67)

I'm sorry I cannot go on today...

Hopping it helps

**Comment by Jean-Romain** [comment]
You're right. I reached the same conclusion.

This works

```r
lazfile <- system.file("extdata", "example.laz", package="rlas")
header = read.lasheader(lazfile)
```

And this don't

```r
lazfile <- system.file("extdata", "extra_byte.laz", package="rlas")
header = read.lasheader(lazfile)
```

**Comment by Jean-Romain** [comment]
I'm slowly converging. The bug comes from `vlrsreader` (you were right but I checked it by security). `readheader.cpp` has not been modified a lot thus I'm pretty sure it comes from this commit: fc0b1419
