### ISSUE TITLE
Shift of Z values in writeLAS output

### ISSUE THREAD

**Issue by floriandeboissieu** [Jean-Romain/rlas#4]
Hi Jean-Romain,
I noticed a 0.01 shift of certain Z values when writing to las/laz, there seem to be a bug there. It seems to be related with some particular Z values, see code below.
Here is how I could reproduce the bug:

> LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
> lidar = readLAS(LASfile)
> writeLAS(lidar,"~/Megaplot.cpy.laz")
365868 bytes written
Column pulseID skipped. It does not meet las specifications.
> lidar1=readLAS("~/Megaplot.cpy.laz")
> any(lidar$Z-lidar1$Z>0)
[1] TRUE
> (lidar$Z-lidar1$Z)[lidar$Z-lidar1$Z>0][1:10]
 [1] 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01

> writeLAS(lidar1,"~/Megaplot.cpy.cpy.laz")
365868 bytes written
Column pulseID skipped. It does not meet las specifications.
> lidar2=readLAS("~/Megaplot.cpy.cpy.laz")
> any(lidar2$Z-lidar1$Z>0)
[1] FALSE

**Comment by floriandeboissieu** [comment]
> LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
> lidar = readLAS(LASfile)
> 
> writeLAS(lidar,"~/Megaplot.cpy.laz")
365868 bytes written
Column pulseID skipped. It does not meet las specifications.
> lidar1=readLAS("~/Megaplot.cpy.laz")
> any(lidar$Z-lidar1$Z>0)
[1] TRUE
> (lidar$Z-lidar1$Z)[lidar$Z-lidar1$Z>0][1:10]
 [1] 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
> writeLAS(lidar1,"~/Megaplot.cpy.cpy.laz")
365868 bytes written
Column pulseID skipped. It does not meet las specifications.
> lidar2=readLAS("~/Megaplot.cpy.cpy.laz")
> any(lidar2$Z-lidar1$Z>0)
[1] FALSE

**Comment by floriandeboissieu** [comment]
Easier to copy paste like this maybe
```
LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
lidar = readLAS(LASfile)
writeLAS(lidar,"~/Megaplot.cpy.laz")
lidar1=readLAS("~/Megaplot.cpy.laz")
any(lidar$Z-lidar1$Z>0)
(lidar$Z-lidar1$Z)[lidar$Z-lidar1$Z>0][1:10]
writeLAS(lidar1,"~/Megaplot.cpy.cpy.laz")
lidar2=readLAS("~/Megaplot.cpy.cpy.laz")
any(lidar2$Z-lidar1$Z>0)
```

**Comment by Jean-Romain** [comment]
Nice

**Comment by Jean-Romain** [comment]
Well, I was all wrong. `set_z` does not take into account the offset and the scale factor. This is not the solution the file is all wrong

**Comment by Jean-Romain** [comment]
Try that one. It's fine on my computer
