### ISSUE TITLE
Las validation

### ISSUE THREAD

**Issue by cyril06** [Jean-Romain/rlas#47]
Hi,

When performing a lascheck on a point cloud with point format set to 7, we have this 

```
error: "Invalid file: the data contains a 'RGB' field but point data format is not set to 2, 3 or 8". 
```

But in the official specification a point format of 7 can have RGB fields.

Regards

**Comment by Jean-Romain** [comment]
Fixed in `rlas 1.3.7`. Thank you for reporting. Please tell me if everything is fine. This bug may be seen at several places including `lascheck`, writeLAS`, `readLAS` but not only I guess.
